# Generated by Django 5.0.14 on 2025-07-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epic',
            name='version',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='version',
        ),
        migrations.RemoveField(
            model_name='task',
            name='version',
        ),
    ]
