# Generated by Django 5.0.14 on 2025-07-15 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_alter_task_table_comment_remove_task_completed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
