# Generated by Django 5.0.14 on 2025-07-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_alter_task_table_comment_epic_task_epic_sprint'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='epic',
            table_comment='holds Epic information',
        ),
        migrations.AlterModelTableComment(
            name='sprint',
            table_comment='holds Sprint information',
        ),
        migrations.AlterModelTableComment(
            name='task',
            table_comment='Holds information about tasks',
        ),
    ]
