# Generated by Django 5.0.14 on 2025-07-15 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_alter_task_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
    ]
