# Generated by Django 5.0.14 on 2025-07-15 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0005_sprint_end_date_after_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('status', 'UNASSIGNED'), ('status', 'IN_PROGRESS'), ('status', 'DONE'), ('status', 'ARCHIVED'), _connector='OR'), name='status_check'),
        ),
    ]
