# Generated by Django 5.0.14 on 2025-07-15 10:59

import django.db.models.functions.comparison
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0006_task_status_check'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(db_comment='The date by which the task should be completed', default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('due_date__gte', django.db.models.functions.comparison.Cast(models.F('created_at'), output_field=models.DateField()))), name='due_date_not_before_created_date'),
        ),
    ]
