# Generated by Django 5.0.14 on 2025-07-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='rirekisho',
        ),
        migrations.CreateModel(
            name='VisitorTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日付')),
                ('daily_visitors', models.PositiveIntegerField(default=0, verbose_name='日別訪問者数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '訪問者追跡',
                'verbose_name_plural': '訪問者追跡',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='セッションキー')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('date', models.DateField(verbose_name='日付')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '訪問者セッション',
                'verbose_name_plural': '訪問者セッション',
                'ordering': ['-created_at'],
                'unique_together': {('session_key', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
