# Generated by Django 5.0.14 on 2025-07-02 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='rirekisho',
        ),
        migrations.AlterModelOptions(
            name='rirekisho',
            options={'ordering': ['-version'], 'verbose_name': 'Statements'},
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
