<<<<<<< HEAD
# Generated by Django 5.0.14 on 2025-07-02 01:29

from django.db import migrations, models
=======
# Generated by Django 5.0.14 on 2025-07-02 23:45

from django.db import migrations
>>>>>>> fec6094 (Refactor notoGarden app: rename to noto_garden, remove unused files, and update settings)


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='rirekisho',
        ),
        migrations.AlterModelOptions(
            name='rirekisho',
<<<<<<< HEAD
            options={'ordering': ['-version'], 'verbose_name': '履歴書', 'verbose_name_plural': '履歴書'},
        ),
        migrations.AddField(
            model_name='rirekisho',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='rirekisho',
            name='personal_statement',
            field=models.TextField(blank=True, verbose_name='statement'),
        ),
        migrations.AlterField(
            model_name='rirekisho',
            name='version',
            field=models.PositiveIntegerField(unique=True, verbose_name='バージョン'),
=======
            options={'ordering': ['-version'], 'verbose_name': 'Statements'},
>>>>>>> fec6094 (Refactor notoGarden app: rename to noto_garden, remove unused files, and update settings)
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
