# Generated by Django 5.0.14 on 2025-07-03 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_workexperience_rirekisho_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rirekisho',
            options={'ordering': ['-version'], 'verbose_name': 'Statement'},
        ),
    ]
