# Generated by Django 5.0.14 on 2025-07-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_rirekisho_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rirekisho',
            name='updated_at',
<<<<<<< HEAD
            field=models.DateTimeField(null=True, blank=True, verbose_name='更新日時'),
=======
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
>>>>>>> 1b750c1 (Refactor notoGarden app: rename to noto_garden, remove unused files, and update settings)
        ),
    ]
