# Generated by Django 5.0.14 on 2025-07-03 23:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_rirekisho_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rirekisho',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='更新日時'),
            preserve_default=False,
        ),
    ]
