# Generated by Django 5.0.14 on 2025-07-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_visitortracking_visitorsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rirekisho',
            options={'ordering': ['-version'], 'verbose_name': '履歴書', 'verbose_name_plural': '履歴書'},
        ),
        migrations.AlterField(
            model_name='rirekisho',
            name='personal_statement',
            field=models.TextField(blank=True, verbose_name='statement'),
        ),
        migrations.AlterField(
            model_name='rirekisho',
            name='version',
            field=models.PositiveIntegerField(unique=True, verbose_name='バージョン'),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
