# Generated by Django 5.0.14 on 2025-07-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='tags',
            field=models.CharField(blank=True, help_text='Separate multiple tags with commas (e.g., personal, reflection, development)', max_length=200),
        ),
    ]
